apiVersion: skaffold/v3alpha1
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  tagPolicy:
    sha256: {}
  local:
    push: false
    useDockerCLI: true
  artifacts:
    - image: ghcr.io/kyh0703/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
      kaniko:
    - image: ghcr.io/kyh0703/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: ghcr.io/kyh0703/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
      kaniko:
    - image: ghcr.io/kyh0703/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
      kaniko:
    - image: ghcr.io/kyh0703/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
      kaniko:
    - image: ghcr.io/kyh0703/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
      kaniko:
