apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: blog
build:
  artifacts:
    - image: 100.100.103.167/kyh0703/client
      context: client
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
    - image: 100.100.103.167/kyh0703/comments
      context: comments
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
    - image: 100.100.103.167/kyh0703/event-bus
      context: event-bus
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
    - image: 100.100.103.167/kyh0703/moderation
      context: moderation
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
    - image: 100.100.103.167/kyh0703/posts
      context: posts
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
    - image: 100.100.103.167/kyh0703/query
      context: query
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
manifests:
  rawYaml:
    - infra/k8s/client-depl.yaml
    - infra/k8s/comments-depl.yaml
    - infra/k8s/event-bus-depl.yaml
    - infra/k8s/ingress-srv.yaml
    - infra/k8s/moderation-depl.yaml
    - infra/k8s/posts-depl.yaml
    - infra/k8s/posts-srv.yaml
    - infra/k8s/query-depl.yaml
