apiVersion: skaffold/v4beta1
kind: Config
build:
  local:
    push: true
  artifacts:
    - image: 100.100.103.167/kyh0703/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    - image: 100.100.103.167/kyh0703/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    - image: 100.100.103.167/kyh0703/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: '**/*.js'
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl:
    defaultNamespace: 'kyh'
